name: Matrix and Parallel Example

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  matrix-test:
    name: Test on ${{ matrix.os }} with Java ${{ matrix.java }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        java: [11, 17]
        exclude:
          - os: windows-latest
            java: 11
        include:
          - os: ubuntu-latest
            java: 8
      fail-fast: false

    steps:
      - name: Checkout code
        uses: checkout
        
      - name: Set up JDK ${{ matrix.java }}
        uses: setup-java
        with:
          java_version: ${{ matrix.java }}
          
      - name: Run platform-specific command
        run: |
          if [ "${{ matrix.os }}" = "ubuntu-latest" ]; then
            echo "Running on Linux with Java ${{ matrix.java }}"
            java -version
          else
            echo "Running on Windows with Java ${{ matrix.java }}"
            java -version
          fi
  
  parallel-steps:
    name: Job with parallel steps
    runs-on: ubuntu-latest
    needs: matrix-test
    
    parallel:
      build-java:
        steps:
          - name: Checkout code
            uses: checkout
            
          - name: Set up JDK
            uses: setup-java
            with:
              java_version: 11
              
          - name: Build with Maven
            uses: maven-build
            with:
              command: "clean package -DskipTests"
      
      build-node:
        steps:
          - name: Checkout code
            uses: checkout
            
          - name: Set up Node.js
            uses: setup-node
            with:
              node_version: 16
              
          - name: Install dependencies
            uses: npm
            with:
              command: ci
    
    steps:
      - name: Final step
        run: echo "All parallel steps completed successfully"
        
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [matrix-test, parallel-steps]
    
    steps:
      - name: Checkout code
        uses: checkout
        
      - name: Deploy application
        run: echo "Deploying application..." 